Repository cornucopia-rs/cornucopia, pull requests merged in 2022-07, with the labels that each got.

#129 Allow double-colon casts
  codegen_test/queries/syntax.sql
  codegen_test/src/cornucopia_async.rs
  codegen_test/src/cornucopia_sync.rs
  cornucopia/src/parser.rs
Labels: enhancement

#126 Remove diesel filter in benchmark
  bench/usage/diesel_benches.rs
Labels: benchmarks

#124 Better codegen
  Cargo.lock
  bench/Cargo.toml
  bench/usage/cornucopia_benches/generated_async.rs
  bench/usage/cornucopia_benches/generated_sync.rs
  codegen_test/Cargo.toml
  codegen_test/src/cornucopia_async.rs
  codegen_test/src/cornucopia_sync.rs
  cornucopia/Cargo.toml
  cornucopia/src/codegen.rs
  cornucopia/src/prepare_queries.rs
  cornucopia/src/run_migrations.rs
  cornucopia/src/validation.rs
  cornucopia_client/Cargo.toml
  examples/auto_build/src/cornucopia.rs
  examples/basic_async/src/cornucopia.rs
  examples/basic_sync/src/cornucopia.rs
  integration/Cargo.toml
  integration/fixtures/errors/validation.toml
  integration/src/main.rs
Labels: enhancement, error reporting

#134 Separate sync async clients
  Cargo.lock
  Cargo.toml
  bench/Cargo.toml
  bench/usage/cornucopia_benches/generated_async.rs
  bench/usage/cornucopia_benches/generated_sync.rs
  clients/async/Cargo.toml
  clients/async/README.md
  clients/async/src/deadpool.rs
  clients/async/src/generic_client.rs
  clients/async/src/lib.rs
  clients/async/src/private.rs
  clients/core/Cargo.toml
  clients/core/README.md
  clients/core/src/array_iterator.rs
  clients/core/src/domain.rs
  clients/core/src/lib.rs
  clients/core/src/utils.rs
  clients/sync/Cargo.toml
  clients/sync/README.md
  clients/sync/src/lib.rs
  clients/sync/src/private.rs
  codegen_test/Cargo.toml
  codegen_test/src/cornucopia_async.rs
  codegen_test/src/cornucopia_sync.rs
  codegen_test/src/main.rs
  cornucopia/src/codegen.rs
  cornucopia/src/type_registrar.rs
  cornucopia_client/Cargo.lock
  cornucopia_client/src/lib.rs
  examples/auto_build/Cargo.toml
  examples/auto_build/src/cornucopia.rs
  examples/basic_async/Cargo.toml
  examples/basic_async/src/cornucopia.rs
  examples/basic_sync/Cargo.toml
  examples/basic_sync/src/cornucopia.rs
Labels: enhancement
